(deftheme kiefciman
  "Created 2023-01-09.")

(custom-theme-set-faces
 'kiefciman
 '(cursor ((t (:background "#7aa2f7"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((t (:foreground "#d9e0ee"))))
 '(homoglyph ((t (:foreground "#7aa2f7"))))
 '(minibuffer-prompt ((t (:foreground "#575268"))))
 '(highlight ((t (:background "#302d41"))))
 '(region ((t (:extend t :background "#abe9b3"))))
 '(shadow ((t (:foreground "#9099c0"))))
 '(secondary-selection ((t (:extend t :foreground "#1a1823" :background "#f28fad"))))
 '(trailing-whitespace ((t nil)))
 '(font-lock-builtin-face ((t (:foreground "#f28fad"))))
 '(font-lock-comment-delimiter-face ((default (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:foreground "#bb9af7"))))
 '(font-lock-constant-face ((t (:foreground "#abe9b3"))))
 '(font-lock-doc-face ((t (:foreground "#575268" :inherit (font-lock-comment-face)))))
 '(font-lock-doc-markup-face ((t (:inherit (font-lock-constant-face)))))
 '(font-lock-function-name-face ((t (:foreground "#7aa2f7"))))
 '(font-lock-keyword-face ((t (:foreground "#bb9af7"))))
 '(font-lock-negation-char-face ((t (:foreground "#f28fad" :inherit (bold)))))
 '(font-lock-preprocessor-face ((t (:foreground "#f8bd96" :inherit (bold)))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#7dcfff" :inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#7dcfff" :inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "#f8bd96"))))
 '(font-lock-type-face ((t (:foreground "#f28fad"))))
 '(font-lock-variable-name-face ((t (:foreground "#7aa2f7"))))
 '(font-lock-warning-face ((t (:inherit (warning)))))
 '(button ((t (:inherit link))))
 '(link ((t (:weight bold :underline (:color foreground-color :style line) :foreground "#abe9b3"))))
 '(link-visited ((t (:foreground "#f8bd96" :inherit (link)))))
 '(fringe ((t (:foreground "#7aa2f7" :inherit (default)))))
 '(header-line ((t (:inherit (mode-line)))))
 '(tooltip ((t (:foreground "#a9b1d6" :background "#13141c"))))
 '(mode-line ((t (:box nil :background "#302d41"))))
 '(mode-line-buffer-id ((t (:foreground "#7aa2f7"))))
 '(mode-line-emphasis ((t (:foreground "#abe9b3"))))
 '(mode-line-highlight ((t (:inherit highlight))))
 '(mode-line-inactive ((t (:box nil :foreground "#575268" :background "#302d41"))))
 '(isearch ((t (:weight bold :inherit (lazy-highlight)))))
 '(isearch-fail ((t (:weight bold :foreground "#414868" :background "#f7768e"))))
 '(lazy-highlight ((t (:background "#7eaead" :foreground "#c0caf5" :weight bold))))
 '(match ((t (:weight bold :foreground "#73daca" :background "#414868"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch)))))
 '(default ((t (:inherit nil :extend nil :stipple nil :background "#000000" :foreground "#c3bac6" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight bold :height 164 :width normal :foundry "CNR " :family "CodeNewRoman Nerd Font")))))

(provide-theme 'kiefciman)
